# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e67836949b237d1b3d1392e7a65da4e26acf1075ab25899244cc18487f9a36773980f9a713a300164ec4628d00df3df8dc98a25a68cc4ae01981e27a61a6f6a

test:
  secret_key_base: 6dbc969e5a3efc5f2dc355d41bfc8589136ed8d1b97c5a8eda5fff477f61e3228c1b74ad212fe9c5068cd730df4af04362b29ff364f16a6a286c150c6e224408

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
